version: '3'

services:
  backend:
    image: book-search-backend
    container_name: bs-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ELASTIC_HOST=http://elasticsearch:9200
      - DEFAULT_PASSWORD=booksearcher
      - CRYPTO_KEY=966efc7f2526829ec7580bfb033652555adcc2bd8fb2a250aaa0ced12bbff00b7b60dd0e323f129171a27d66660af93b258eab90507ff28895fb79b459ced1f2

  frontend:
    image: book-search-frontend
    container_name: bs-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4080:80"

  elasticsearch:
    image: book-search-elasticsearch
    container_name: bs-search
    build:
      context: ./
      dockerfile: Dockerfile-elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"

volumes:
  esdata:
